# Generated by Django 4.1.1 on 2022-09-17 22:29

import django.core.validators
from django.db import migrations, models
import dl_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('public_id', models.SlugField(max_length=18, unique=True)),
                ('file', models.FileField(upload_to=dl_models.models.model_file_path)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
