# Generated by Django 4.1.2 on 2022-12-05 04:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('public_id', models.SlugField(max_length=18, unique=True)),
                ('framework', models.CharField(max_length=12)),
                ('architecture', models.JSONField(default=dict)),
                ('path', models.CharField(max_length=300)),
                ('weights_path', models.CharField(max_length=300)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DLModelDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('dlmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dl_models.dlmodel')),
            ],
        ),
        migrations.AddField(
            model_name='dlmodel',
            name='datasets',
            field=models.ManyToManyField(through='dl_models.DLModelDataset', to='datasets.dataset'),
        ),
    ]
