# Generated by Django 4.1.4 on 2022-12-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlmodel',
            name='loss_function',
            field=models.CharField(default='mse', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlmodel',
            name='optimizer',
            field=models.CharField(default='Adam', max_length=15),
            preserve_default=False,
        ),
    ]
