# Generated by Django 4.1.2 on 2022-11-14 20:16

import django.core.files.storage
from django.db import migrations, models
import dl_models.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('dl_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlmodel',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/AlexisAndradeDev/Deep Learning API/Deep-Learning-API/dl_api/private')), upload_to=dl_models.models.model_file_path),
        ),
    ]
