name: Integration Tests

on:
  push:
    branches: 
      -"main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        node-version: ["18.x"]

    steps:
    - uses: actions/checkout@v3

    - name: Install Netcat
      run : |
        sudo apt-get install netcat

    - name: Install Node JS ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: "x64"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linux.txt
        sudo apt-get install libmagic1
        pip install python-magic
      
    - name: Install Newman dependency
      run: |
        npm install -g newman

    - name: Run Postman Integration Tests
      run: |
        cd dl_api
        export DJANGO_ENV=integration_test
        python manage.py runserver & cd ../integration_tests/postman && echo "Waiting for server to run on 8000 (timeout: 15 seconds)..." && timeout 15 sh -c 'until nc -z localhost 8000; do sleep 1; done' && newman run cats_and_dogs.postman_collection.json -e deep-learning-api-env.postman_environment.json
